name: Minecraft Server Manager
description: A single init script which makes running multiple Minecraft/Bukkit servers easier for us admins.
maintainer: Steeve Gaudreault-Lambert <steevegl.dev@gmail.com>
URL:
version: 0.1
category: "Entertainment"
license: 