.catalog:
  name: Template Stack
  version: 0.1
  description: |
    Template Stack description.
  uuid: temp-stack-0
  questions:
    - variable: "Variable-string"
      description: "Template Stack's Variabl-string description."
      label: "string:"
      required: true
      default: 1
      type: "string"
  questions:
    - variable: "Variable-int"
      description: "Template Stack's Variabl-int description."
      label: "int:"
      required: true
      default: 1
      type: "int"
  questions:
    - variable: "Variable-boolean"
      description: "Template Stack's Variabl-boolean description."
      label: "boolean:"
      required: true
      default: 1
      type: "boolean"
  questions:
    - variable: "Variable-password"
      description: "Template Stack's Variabl-password description."
      label: "password:"
      required: true
      default: 1
      type: "password"
  questions:
    - variable: "Variable-service"
      description: "Template Stack's Variabl-service description."
      label: "service:"
      required: true
      default: 1
      type: "service"
  questions:
    - variable: "Variable-service"
      description: "Template Stack's Variabl-service description."
      label: "service:"
      required: true
      default: 1
      type: "service"
  questions:
    - variable: "Variable-enum"
      label: "enum"
      description: "Template Stack's Variabl-enum description."
      type: enum
      options: # List of options if using type of `enum`
        - Option 1
        - Option 2
  questions:
    - variable: "Variable-certificate"
      label: "certificate"
      description: "Template Stack's Variabl-certificate description."
      type: "certificate"